version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:Gnrx7+5PFIs3m6enbUgSrmgddNVTr8cxKroj8aIeU8Y=
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=inventory
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - QUEUE_CONNECTION=database
    depends_on:
      - db
    volumes:
      - storage:/var/www/html/storage/app
      - logs:/var/www/html/storage/logs

  db:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=rootsecret
      - MYSQL_DATABASE=inventory
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
  storage:
  logs:
